version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.8"  # Especifica la versión de Python

sphinx:
  configuration: docs/source/conf.py  # Ruta al archivo conf.py

python:
  install:
    - requirements: requirements.txt
