version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.8"  # Especifica la versión de Python

sphinx:
  configuration: docs/conf.py  # Ruta al archivo conf.py

python:
  version: 3.8  # Versión de Python compatible con las dependencias
  install:
    - requirements: requirements.txt
