version: 2

sphinx:
  configuration: docs/conf.py  # Ajusta la ruta al archivo conf.py en tu proyecto

python:
  version: 3.9  # Ajusta a la versión de Python requerida por tu proyecto
  install:
    - requirements: requirements.txt  # Asegúrate de tener este archivo con tus dependencias
