version: 2

# Build tools and environments
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

# Python dependencies
python:
  install:
    - requirements: requirements.txt

# Sphinx documentation build
sphinx:
  configuration: docs/source/conf.py
