version: 2

sphinx:
  configuration: docs/conf.py  # Ruta al archivo conf.py

python:
  version: 3.9  # Versión de Python compatible con las dependencias
  install:
    - requirements: requirements.txt
